# Generated by Django 2.2.5 on 2019-12-14 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('normal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='msg',
            field=models.TextField(max_length=99999),
        ),
        migrations.AlterField(
            model_name='message',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
